/**
 * Shared decoration constants between client and server
 */
import { DecorationType, rarityLevels } from "../index.js";
import { s3URL } from "./plotConfig.js";

const baseUrl = `${s3URL}/decorations`;

export const decorations: Record<number, DecorationType> = {
  1: {
    id: 1,
    name: "Pink Pig",
    cost: 100,
    icon: `${baseUrl}/Pig-icon.png`,
    imageSrc: `${baseUrl}/Pig.png`,
    rarity: rarityLevels[0],
    description: "It has a curly tail.",
  },
  2: {
    id: 2,
    name: "Party Pig",
    cost: 2000,
    icon: `${baseUrl}/Party-Pig-icon.png`,
    imageSrc: `${baseUrl}/Party-Pig.png`,
    rarity: rarityLevels[1],
    description: "It's here to party.",
  },
  3: {
    id: 3,
    name: "Rainbow Pig",
    cost: 8000,
    icon: `${baseUrl}/Rainbow-Pig-icon.png`,
    imageSrc: `${baseUrl}/Rainbow-Pig.png`,
    rarity: rarityLevels[1],
    description: "It ate a leprachaun. It's fine.",
  },
  4: {
    id: 4,
    name: "Golden Pig",
    cost: 20000,
    icon: `${baseUrl}/Golden-Pig-icon.png`,
    imageSrc: `${baseUrl}/Golden-Pig.png`,
    rarity: rarityLevels[2],
    description: "Favorite food: Golden truffle mushrooms.",
  },
  5: {
    id: 5,
    name: "Bird House",
    cost: 100,
    icon: `${baseUrl}/Bird-House-icon.png`,
    imageSrc: `${baseUrl}/Bird-House.png`,
    rarity: rarityLevels[0],
    description: "A cozy home for birds.",
  },
  6: {
    id: 6,
    name: "Rainbow Bird House",
    cost: 8000,
    icon: `${baseUrl}/Rainbow-Bird-House-icon.png`,
    imageSrc: `${baseUrl}/Rainbow-Bird-House.png`,
    rarity: rarityLevels[1],
    description: "Warning: May cause excessive chirping.",
  },
  7: {
    id: 7,
    name: "Golden Bird House",
    cost: 20000,
    icon: `${baseUrl}/Golden-Bird-House-icon.png`,
    imageSrc: `${baseUrl}/Golden-Bird-House.png`,
    rarity: rarityLevels[2],
    description: "Fancy? Yes. Practical? No.",
  },
  8: {
    id: 8,
    name: "Gnome",
    cost: 200,
    icon: `${baseUrl}/Gnome-icon.png`,
    imageSrc: `${baseUrl}/Gnome.png`,
    rarity: rarityLevels[0],
    description: "A friendly little gnome.",
  },
  9: {
    id: 9,
    name: "Cowboy Hat Gnome",
    cost: 2000,
    icon: `${baseUrl}/Cowboy-Gnome-icon.png`,
    imageSrc: `${baseUrl}/Cowboy-Gnome.png`,
    rarity: rarityLevels[1],
    description: "It loves drinking tumbleweed tea.",
  },
  10: {
    id: 10,
    name: "Rainbow Gnome",
    cost: 8000,
    icon: `${baseUrl}/Rainbow-Gnome-icon.png`,
    imageSrc: `${baseUrl}/Rainbow-Gnome.png`,
    rarity: rarityLevels[1],
    description: "Very bad at hide and seek.",
  },
  11: {
    id: 11,
    name: "Golden Gnome",
    cost: 20000,
    icon: `${baseUrl}/Golden-Gnome-icon.png`,
    imageSrc: `${baseUrl}/Golden-Gnome.png`,
    rarity: rarityLevels[2],
    description: "A solid gold gnome. Very expensive.",
  },
  12: {
    id: 12,
    name: "Basic Scarecrow",
    cost: 100,
    icon: `${baseUrl}/Scarecrow-icon.png`,
    imageSrc: `${baseUrl}/Scarecrow.png`,
    rarity: rarityLevels[0],
    description: "It's not very scary, is it?",
  },
  13: {
    id: 13,
    name: "Robot Scarecrow",
    cost: 5000,
    icon: `${baseUrl}/Robot-Scarecrow-icon.png`,
    imageSrc: `${baseUrl}/Robot-Scarecrow.png`,
    rarity: rarityLevels[1],
    description: "Comes with built in WiFi.",
  },
  14: {
    id: 14,
    name: "Golden Scarecrow",
    cost: 20000,
    icon: `${baseUrl}/Golden-Scarecrow-icon.png`,
    imageSrc: `${baseUrl}/Golden-Scarecrow.png`,
    rarity: rarityLevels[2],
    description: "Gardeners travel far and wide to see it.",
  },
  15: {
    id: 15,
    name: "Rabbit",
    cost: 200,
    icon: `${baseUrl}/Bunny-icon.png`,
    imageSrc: `${baseUrl}/Bunny.png`,
    rarity: rarityLevels[0],
    description: "A bouncy creature with a puffy tail.",
  },
  16: {
    id: 16,
    name: "Frog",
    cost: 400,
    icon: `${baseUrl}/Frog-icon.png`,
    imageSrc: `${baseUrl}/Frog.png`,
    rarity: rarityLevels[0],
    description: "TBD",
  },
  17: {
    id: 17,
    name: "Dog",
    cost: 800,
    icon: `${baseUrl}/Dog-icon.png`,
    imageSrc: `${baseUrl}/Dog.png`,
    rarity: rarityLevels[0],
    description: "TBD",
  },
};
